version: 2.1

jobs:
  maven_test:
    docker:
      - image: cimg/openjdk:21.0.0
    steps:
      - checkout
      - run:
          command: mvn validate
          name: Run google checkStyle
          working_directory: ./riceCooker
      - run:
          command: mvn test
          name: Run test
          working_directory: ./riceCooker
workflows:
  maven_test:
    jobs:
      - maven_test
