version: 2.1
orbs:
  go: circleci/go@1.7.3

jobs:
  build_and_test:
    executor:
      name: go/default
      tag: "1.19.2"
    steps:
      - checkout
      - go/test:
          covermode: atomic
          failfast: true
          race: true

workflows:
  test:
    jobs:
      - build_and_test
